### ISSUE TITLE
Admin Place Order

### ISSUE THREAD

**Issue by devkaranpatidar** [sohelrana09/magento2-module-delivery-date#3]
Its not working when admin order place from admin panel

**Comment by devkaranpatidar** [comment]
![screenshot from 2017-10-12 14-51-29](https://user-images.githubusercontent.com/22830904/31488981-ff82c14e-af5c-11e7-824b-26c2c3456753.png)
![screenshot from 2017-10-12 14-49-16](https://user-images.githubusercontent.com/22830904/31488999-0a59c6b2-af5d-11e7-97a5-30e6083ba3de.png)

**Comment by devkaranpatidar** [comment]
first screen sort for admin its not working and second is grate its working.

**Comment by sohelrana09** [comment]
This is done and added to master branch
